apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k3s-wordpress-deployment-monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/programmingtothecore/K3sWordpressDeployemntMonitoring  # Your GitHub repo URL
  ref:
    branch: main  # Correct field to specify the branch
