apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wordpress-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: K3sWordpressDeployemntMonitoring
  targetNamespace: flux-system
