apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: wordpress-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./clusters/my-cluster"  # Make sure this path is correct
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-wordpress-deployment-monitoring
  targetNamespace: flux-system
